// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfcnrglreufvmacvsaak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmY25yZ2xyZXVmdm1hY3ZzYWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTU1MzAsImV4cCI6MjA1OTYzMTUzMH0.61o57Hj1M1N2sxB-DvHo8ox07SO_9Ci5NtiNnULK_Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);